---
- include: install-dnf.yml
  when: "ansible_os_family == 'RedHat'"

- include: install-pip.yml
  when: "ansible_os_family != 'RedHat'"

- name: "ensure powerline is loaded in shell"
  template:
    src: powerline.sh.j2
    dest: /etc/profile.d/powerline.sh
  sudo: yes

- name: "ensure default top theme for powerline is configured"
  lineinfile:
    dest: "{{ powerline_config_file }}"
    line: "\t\t\"default_top_theme\": \"{{ powerline_default_top_theme }}\","
    regexp: "default_top_theme"
    insertbefore: "term_truecolor"
  sudo: yes

- name: "ensure powerline for shell is configured"
  template:
    src: powerline-shell.json.j2
    dest: "{{ powerline_themes_directory }}/shell/default.json"
  sudo: yes

- name: "ensure powerline for tmux is configured"
  template:
    src: powerline-tmux.json.j2
    dest: "{{ powerline_themes_directory }}/tmux/default.json"
  sudo: yes
